faiss_db: 
  collection_name: "docment_portal"
embedding_model: 
  provider: "google"
  model_name: "text-embedding-004"

retriever: 
  top_k: 10
  search_type: "similarity"

llm:
 groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llma-70b"
    temperature: 0
    max_tokens: 2048
google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_tokens: 2048
